//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMAShop.WebUI.Views.Resources.Information {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GMAShop.WebUI.Views.Resources.Information.Index_fr", typeof(Index_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Merhaba {
            get {
                return ResourceManager.GetString("Merhaba", resourceCulture);
            }
        }
        
        internal static string Bugün {
            get {
                return ResourceManager.GetString("Bugün", resourceCulture);
            }
        }
        
        internal static string Hava {
            get {
                return ResourceManager.GetString("Hava", resourceCulture);
            }
        }
        
        internal static string Çok {
            get {
                return ResourceManager.GetString("Çok", resourceCulture);
            }
        }
        
        internal static string Sıcak {
            get {
                return ResourceManager.GetString("Sıcak", resourceCulture);
            }
        }
    }
}
